### ISSUE TITLE
valhalla routing fails

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#355]
I am using the latest sdk 4.3.0.RC2 and the `PackageManagerValhallaRoutingService`
I download the package for my region and when i run a route request in that region i get: 
```
Exception while calculating route: No suitable edges near location
```
To debug the thing here is what i have done:
* download both the map package and the route package to make sure we are in the same region
* custom build the sdk to log the actual valhalla request parameters 
```
:CalculateRoute params: {"costing":"pedestrian","locations":[{"lat":45.164395600397178,"lon":5.7217887942269865},{"lat":45.176524560400956,"lon":5.7537675251489491}],"units":"kilometers"}
```
They are good and correspond to the region and positions i asked for
* built my own valhalla vtiles package and got the same error
* run the valhalla service on the tiles used to build the vtiles and then it works correctly.

What i suspect is for your valhalla ids (column/row) to not be good in db.
What bugs me is that if i compare your columns/rows in vtiles they do not correspond to the ids i am seeing in valhalla tiles folder.
Where did you find the rules about columns/rows valhalla graphreader expects in the db?

**Comment by farfromrefug** [comment]
Should add that it needs more tests on my side. I am debugging this right now

**Comment by mtehver** [comment]
Thanks. Which offline package did you download? Note that currently custom area packages (defined by bounding box) do not work with 4.3.0RC versions. The server side is not yet set up.

**Comment by farfromrefug** [comment]
@mtehver every tests i am doing are with `FR-V`. I t corresponds to region around 45.1941, 5.7306
So i can confirm it is not working either with `PackageManagerValhallaRoutingService`

I am testing on the emulator, the vtiles is here but it seems that it cant find anything. 
I am trying to add logs to see which valhalla tiles it is trying to get from the db (level, row, column)
<img width="1646" alt="Screen Shot 2020-04-21 at 10 52 37" src="https://user-images.githubusercontent.com/655344/79846130-54ec0400-83be-11ea-912a-9aa271b3e41e.png">

**Comment by farfromrefug** [comment]
@mtehver sorry to bother you but is there any place we can chat? i see that you commented a lot of code in valhalla which will break what i am trying to do (getting elevation profile for example)

**Comment by mtehver** [comment]
@farfromrefug It seems that other packages are also broken, not just FR-V. I will take a closer look at this, perhaps the issue is with the package processing script. Fortunately this does not affect Valhalla 2 packages that use different endpoint. So this is just 4.3.0RC issue.

Regarding chat channel, I am not able to provide one, sorry. We do have internal Slack/Skype channels, but I check them once a day, so they are not more effective than github/e-mail really.

About Valhalla changes. There were 3 types of changes, if I remember correctly. First, changes to make Valhalla compile in C++11 mode on Android, iOS and Windows. Second, changes to fix somewhat sloppy code that used to crash when some graph edges were missing. Third, removing some parts not relevant to the SDK and that needed file system access for external files. If I am not mistaken, the elevation support required additional external DEM database that is really large (about 2TB for the whole planet). That part is not really a good fit for mobile devices. Some of the changes (crash fixes) should be compiled together into a pull request and merged upstream with the main code. Unfortunately this is quite time consuming and we had relatively bad experience doing this with Valhalla 2.

**Comment by farfromrefug** [comment]
@mtehver good to know you see the error on your side.

About chat don't worry i understand,

About valhalla yes this is what i saw. I was thinking about adding elevation hgt in another table in the vtiles but now i think it is not the best idea.
I am thinking about a totally new approach to get elevation profile. I am thinking about implementing [this](https://labs.mapbox.com/bites/00009/) in Carto as special raster layout that would know how to draw terrain rgb tiles. The idea behing is that i could possibly get hillshade (even dynamic ones) but also elevation profile as the tiles are actually raw elevation.
I still have a question about precision but can't really know right now.

**Comment by mtehver** [comment]
@farfromrefug The issue was related to 'build_valhalla_tiles.py' script, I published an older version of it that stored wrong format tag in 'metadata' table. The script is now fixed. I have also re-uploaded the packages, but CDN cache is currently still pointing to old packages.

**Comment by farfromrefug** [comment]
@mtehver so tried to use your change with migration to gph3. Did not work:
* i still need to change the way you get valhalla tiles id because with your script my vtiles is empty. With the PR i send it works though it says some tiles are missing
* when i use that vtiles in `ValhallaOfflineRoutingService` i still get the error:
```
System.err: java.lang.RuntimeException: Exception while calculating route: No suitable edges near location
System.err:     at com.carto.routing.PackageManagerValhallaRoutingServiceModuleJNI.PackageManagerValhallaRoutingService_calculateRouteSwigExplicitPackageManagerValhallaRoutingService(Native Method)
System.err:     at com.carto.routing.PackageManagerValhallaRoutingService.calculateRoute(PackageManagerValhallaRoutingService.java:141)
System.err:     at com.akylas.carto.additions.AKRoutingServiceAdditions$1.run(AKRoutingServiceAdditions.java:27)
System.err:     at java.lang.Thread.run(Thread.java:919)
```

**Comment by farfromrefug** [comment]
have yoy tried without the package service and with creating a small vtiles based on a quite small `.osm.pbf` file?

**Comment by mtehver** [comment]
Can you elaborate a bit? The updated packages are now available from the server, and it seems they are working fine. How did you generate you package that had no tiles? Did you use custom tile mask?

**Comment by farfromrefug** [comment]
@mtehver can you share your valhalla config file? i can see strange differences  in our vtiles. Like some of your "tiles" inside the vtiles are much bigger for you

**Comment by farfromrefug** [comment]
@mtehver never mind got it work! Didn't think so but the order of tiles in the vtiles were important.
That + the gph3 and now it works!

Awesome work again. Thanks!
