### ISSUE TITLE
[GeoJSONVectorTileDataSource]map not refreshing after setLayerGeoJSON

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#443]
There is an issue with the "refreshing" of a `VectorTileLayer` after calling the first `setLayerGeoJSON`
It randomly wont refresh.
The same behavior happens on iOS/Android

I tried to force a map refresh after but it wont always work. 

You should be abe to reproduce it by simply adding the datasource/layer/geojson after the map is initialised

**Comment by mtehver** [comment]
Thanks for reporting this, should be fixed now in master.

**Comment by farfromrefug** [comment]
@mtehver i love how fast you are :D thanks!

**Comment by mtehver** [comment]
Fix is in 4.4.1. Closing the issue.

**Comment by farfromrefug** [comment]
@mtehver i would like to reopen that issue. I still see it on iOS with 4.4.1.1. Even on android i am not 100% sure it always work. Seems like if i create/add the layer after adding the geojson it does not work.
On iOS it never works right now

**Comment by mtehver** [comment]
@farfromrefug Could you make a small test demonstrating this? It could be data-related. 

The bug I fixed in 4.4.1 was related to layer bounds not being recalculated when updating geojson. Perhaps there is another case causing this.

**Comment by farfromrefug** [comment]
@mtehver i did not manage to reproduce it with a simple Obj C project.
My apps use Nativescript and thus a javascript/Obj-C bridge.
In the process of testing it i realised that adding a 0 timeout fixed it. This is still weird cause i add the geosjon after an http call so completely async. I also checked and the call is made in the main thread.
For now i will close it again as i cant find the real source of the issue, so cant tell if it is carto side or Nativescript side or my side.
Thanks again for taking the time to answer this!
